Fix NSIDC download issues
evetion/SpaceLiDAR.jl pull request #27
Opened 2022-10-18 15:23 UTC by alex-s-gardner

2022-10-18 16:39 UTC, evetion requested changes

2022-10-18 16:39 UTC, evetion commented on src/utils.jl
> -        write(f, "machine n5eil01u.ecs.nsidc.org login $username password $(password)\n")
I think this is the only change needed in this PR.

2022-10-20 03:58 UTC, alex-s-gardner commented
Sorry for all the commits, I've now discovered `]dev` so my pull request etiquette should improve

2022-10-20 06:32 UTC, evetion commented
No problem, but you're doing everything in the same branch. As in this PR/branch you have:

- Fix for ICESat-2 download (original issue, PR title)
- EarthDataCloud search (and adding the search bbox to those granules)
- Bounding box filtering on ATL06

Ideally those are separate PRs, that makes it easier to discuss a single issue and merge when ready. Now we can't merge the download fix, because the other parts are unfinished.

2022-10-20 16:20 UTC, closed without merging

2022-10-20 16:20 UTC, alex-s-gardner commented
I'll clean this up before requesting a pull